import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import About from '../src/components/About';
import { Box, Flex } from '@mantine/core';
import Hero from '../src/components/Hero';
import Education from '../src/components/Education';
import WorkExperience from '../src/components/WorkExperience';
import PersonalProjects from '../src/components/PersonalProjects';
import TechSkills from '../src/components/TechSkills';
import OtherSkills from '../src/components/OtherSkills';
import Languages from '../src/components/Languages';
import Quote from '../src/components/Quote';
import Contact from '../src/components/Contact';
import { fetchResume } from '../src/store/actions/resume.action';
import { connect } from 'react-redux';
import { useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

function Home(props: any) {
  const resumeData = props.resumeData;
  const data = fetchResume();
  useEffect(() => {
    console.log(resumeData);
  }, [props.resumeData]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* className={inter.className} */}
      <Flex justify={'center'} align={'center'} direction={'column'} gap={32}>
        <Hero />
        <About />
        <Education />
        <WorkExperience />
        <PersonalProjects />
        <TechSkills />
        <OtherSkills />
        <Languages />
        <Quote />
        {/* <Contact /> */}
      </Flex>
    </>
  );
}

const mapStateToProps = (state: any) => ({
  resumeData: state.resumeData,
});

const mapDispatchToProps = (dispatch: any) => ({
  fetchResume: () => dispatch(fetchResume()),
});

export default connect(mapStateToProps, mapDispatchToProps)(Home);
